version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      NODE_ENV: development
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      POKEMON_API: ${POKEMON_API}
      POKEMON_IMAGE_API: ${POKEMON_IMAGE_API}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start